[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[dev]
  command = "npm run start:react"
  port = 8888
  targetPort = 3000
  framework = "#auto"
